apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculate
  template:
    metadata:
      labels:
        app: calculate
    spec:
      containers:
      - image: okteto/calculate:golang
        name: calculate
        resources:
          limits:
            cpu: 8Gi
            memory: 8Gi
