services:
    ubuntu:
        public: true
        container_name: tzchz
        image: imlala/ubuntu-xfce-vnc-novnc:latest
        ports:
            - 6080:6080
        environment: 
            - VNC_PASSWD=gaskan
            - GEOMETRY=1280x768
            - TZ=Asia/Shanghai
            - DEPTH=24
        volumes: 
            - /root/Desktop
            - /home
        resources:
          cpu: 8000m
          memory: 8000Mi
          storage:
            size: 2Gi
            class: ssd
